version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: isax01
      POSTGRES_PASSWORD: isax
      POSTGRES_DB: mail
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  app:
    build:
      context: ./app
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/usr/src/app
    command: npm start
